name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

env:
  BCC_VERSION: ec49363e2e9daec026ee6cae4c5fc316f8fab0ff
  GO_VERSION: 1.21.3
  INSTALL_GO: "true"
  INSTALL_BCC: "true"
  DEBIAN_RELEASE: bookworm

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-20.04
    outputs:
      kernel_versions: ${{ steps.kernel_versions.outputs.value }}
      target_arches: ${{ steps.target_arches.outputs.value }}
      version_tag: ${{ steps.version_tag.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format version tag
        shell: bash
        id: version_tag
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "value=$TAG" >> $GITHUB_OUTPUT

      - name: Target Kernel Versions
        id: kernel_versions
        run: |
          KERNEL_VERSIONS=($(curl -sSL https://raw.githubusercontent.com/vietanhduong/kernel-builder/master/KERNEL_VERSIONS))
          echo "value=$(printf '%s\n' "${KERNEL_VERSIONS[@]}" | jq -ncR '[inputs | select(length>0)]')" >> $GITHUB_OUTPUT

      - name: Target Arches
        id: target_arches
        # Currently we just support for x86-64
        run: |
          ARCHES=(amd64)
          echo "value=$(printf '%s\n' "${ARCHES[@]}" | jq -ncR '[inputs | select(length>0)]')" >> $GITHUB_OUTPUT

  build-sysroot:
    name: Build Sysroot
    runs-on: ubuntu-20.04
    needs: prepare
    strategy:
      matrix:
        arch: ${{ fromJson(needs.prepare.outputs.target_arches) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Sysroot Arch ${{ matrix.arch }}
        env:
          DOCKER_BASE_IMAGE: sysroot
          ARCH: ${{ matrix.arch }}
        run: |
          BUILDS_DIR=$PWD/.builds
          mkdir -p $BUILDS_DIR

          docker build . -t $DOCKER_BASE_IMAGE \
            --build-arg BCC_VERSION="${BCC_VERSION}" \
            && docker run --rm -v $BUILDS_DIR:/builds -v ./build-sysroot.sh:/scripts/build-sysroot.sh \
                -e INSTALL_GO=${INSTALL_GO} \
                -e INSTALL_BCC=${INSTALL_BCC} \
                -e GO_VERSION="${GO_VERSION}" \
                $DOCKER_BASE_IMAGE -a "$ARCH" -r "${DEBIAN_RELEASE}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/.builds/sysroot-${{matrix.arch}}.tar.gz

  build-disk:
    name: Build QEMU Disk
    runs-on: ubuntu-20.04
    needs:
      - prepare
      - build-sysroot
    strategy:
      matrix:
        arch: ${{ fromJson(needs.prepare.outputs.target_arches) }}
        kernel_version: ${{ fromJson(needs.prepare.outputs.kernel_versions) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install QEMU
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get update && sudo apt-get install -y qemu-system

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}

      - name: Build disk with Kernel Version ${{ matrix.kernel_version }}
        shell: bash
        env:
          KERNEL_VERSION: ${{ matrix.kernel_version }}
          SYSROOT: "${{ github.workspace }}/artifact/sysroot-${{matrix.arch}}.tar.gz"
          DISK_SIZE: "4096M"
        run: ./build-disk.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/.builds/qemu-${{matrix.kernel_version}}.qcow2

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs:
      - prepare
      - build-disk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}

      - name: Build Release Body
        shell: bash
        run: |
          KERNEL_VERSIONS=($(curl -sSL https://raw.githubusercontent.com/vietanhduong/kernel-builder/master/KERNEL_VERSIONS))
          # KERNEL SECTION
          md="## Support Kernel Version\n"
          for version in "${KERNEL_VERSIONS[@]}"; do
            md+="* $version\n"
          done
          # DEBIAN SECTION
          md+="## Debian\n"
          md+="### Release: \`${DEBIAN_RELEASE}\`\n"
          # BCC SECTION
          if [[ $INSTALL_BCC = true ]]; then
            md+="## BCC\n"
            md+="### Commit: \`${BCC_VERSION}\`\n"
          fi
          # GO SECTION
          if [[ $INSTALL_GO = true ]]; then
            md+="## Go\n"
            md+="### Version: \`${GO_VERSION}\`\n"
          fi
          echo -ne "$md" > ${{ github.workspace }}/body.md

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/artifact/*.qcow2"
          bodyFile: ${{ github.workspace }}/body.md
          tag: ${{ needs.prepare.outputs.version_tag }}
